### ISSUE TITLE
Correcciones de Mercado Liebre

### ISSUE THREAD

**Issue by Sofi231098** [MicaReynoso/Mercado_Liebre#1]
-[]1 - Cumple, tiene todo los elementos requeridos.
-[]2 - Cumple, todos los iconos estan centrados y con un tamaño de 2rm.
-[]3 - Cumple, funciona para todas las resoluciones.
-[]4 -Cumple, la pagina cuenta con un formulatio de registro.
-[]5 - Cumple, el formulario si cuenta con un formulario para loguearse.
-[]6 -Cumple, si muestra los mensajes cuando se ingresa información equivocada.
-[]7 - No cumple, el search bar no esta dentro de un form.
-[]8 -Cumple, si usa animaciones y propiedades de transición en css.
-[]9 - Utilizó bastante bien las animaciones, la resolucion en distintas pantallas es buena, hizo un buen maquetado y toda la pagina se ve bien estructurada.
-[]10 - Las letras del navegador, para pantallas mas grandes, podrían sermás grandes. Se podría arreglar las palabras que se subrayan.

**Comment by MicaReynoso** [comment]
solucionado el problema del subrayado
